language: node_js
sudo: required
dist: trusty

env:
  global:
    - "FTP_USER=luigiplr@metalmoshpit.net"
    - "FTP_PASSWORD=alexandria"

node_js:
  -  stable

before_install:
  -  echo -e "deb http://ppa.launchpad.net/pali/pali/ubuntu precise main\ndeb-src http://ppa.launchpad.net/pali/pali/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  -  sudo apt-get update -y --force-yes
  -  sudo apt-get install ncftp nsis -y --force-yes
install:
  -  npm install --no-optional
  -  grunt clean:all
script:
  -  mkdir release && chmod -R 755 util
  -  util/linux.sh
after_success:
  - ls -sh release
  - ncftpput -R -v -u $FTP_USER -p $FTP_PASSWORD ftp.gridhost.co.uk /slackie/travis/ release/*

