language: node_js
sudo: required
node_js:
  -  stable
before_install:
  -  echo -e "deb http://ppa.launchpad.net/pali/pali/ubuntu precise main\ndeb-src http://ppa.launchpad.net/pali/pali/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  -  sudo apt-get update -y --force-yes
  -  sudo apt-get install nsis -y --force-yes
install:
  -  npm install --no-optional
script:
  -  grunt clean:all && mkdir release
  -  chmod +x util/travis/windows.sh && ./util/travis/windows.sh
deploy:
  provider: releases
  api_key: "9dc512803e5f9be359f723f698695a177e10062b"
  file: "releases/*/**"
  skip_cleanup: true
  on:
    tags: true