language: node_js'
sudo: required
node_js:
  -  stable
before_install:
  -  echo -e "deb http://ppa.launchpad.net/pali/pali/ubuntu precise main\ndeb-src http://ppa.launchpad.net/pali/pali/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  -  sudo apt-get update --force-yes
  -  sudo apt-get install nsis --force-yes
install:
  -  npm install --no-optional
script:
  -  grunt clean:all && mkdir release