language: node_js
node_js:
  - "stable"
before_install:
  - 'echo -e "deb http://ppa.launchpad.net/pali/pali/ubuntu precise main\ndeb-src http://ppa.launchpad.net/pali/pali/ubuntu precise main" | tee -a /etc/apt/sources.list'
  -  "apt-get update -y && apt-get install nsis -y"
install:
  -  "npm install --no-optional"
script:
  -  "grunt clean:all && mkdir release"